### ISSUE TITLE
Cant seem to be able to get it to work

### ISSUE THREAD

**Issue by asgeirtj** [itcon-pty-au/typingmind-cloud-backup#1]
![image](https://github.com/user-attachments/assets/6a4cec9f-454d-482a-bcab-ed8b7c61edfe)

**Comment by itcon-pty-au** [comment]
What is the error you see in the dev console? Can you share the same?

**Comment by itcon-pty-au** [comment]
> I'm getting the same error. I'm trying to backup to an existing S3 bucket I have already. Is that a problem?

If the backup was not created by this extension, it may not work.

**Comment by jph112233** [comment]
Same error for me.  Thanks for building this!

**Comment by itcon-pty-au** [comment]
@nigelp, @jph112233, @asgeirtj  - This should be fixed now. Can you try once again and feedback please?

**Comment by nigelp** [comment]
Sorry, no change. Still the same error message for me after a restart of the extension.

**Comment by itcon-pty-au** [comment]
@nigelp - Are you still trying with the s3 backup file that was created outside of this extension? If yes, it will not work. I suggest you create a new bucket and create a fresh backup file using the extension.

**Comment by itcon-pty-au** [comment]
@asgeirtj - Could you retry? The fix is in now and it should be working.

**Comment by nigelp** [comment]
I've tried re-installing the extension. I've created a new bucket. Even created a new account and new bucket. Set all the permissions for public access, and still getting this Invalid AWS details. I have never tried to upload an existing backup, I'm trying to create the first backup.

**Comment by itcon-pty-au** [comment]
ok, that is the issue. 

The reason is to secure your S3 bucket. If you take the time to setup the permissions and in the scenario where the access key gets leaked (its being stored in your browser, which is not at all secure), hackers can only get till this typingmind bucket, otherwise, damage will be bigger.

**Comment by nigelp** [comment]
Ah I understand. Well I'm afraid it's a complexity too far for me. I've uninstalled now. I'll wait for something to come along which offers a simpler on-boarding for us muppets. :)

**Comment by jph112233** [comment]
Thanks for developing this!  

I am still getting the same error. I am able to get it working on a diff computer and my phone, but when I try on a another computer I still get the error

**Comment by itcon-pty-au** [comment]
> Thanks for developing this!
> 
> I am still getting the same error. I am able to get it working on a diff computer and my phone, but when I try on a another computer I still get the error

Can you delete the entire browser history and try this again?

**Comment by itcon-pty-au** [comment]
Closing as there is no further feedback received.
